### ISSUE TITLE
BUGLIST / TODO-LIST Benutzerseite

### ISSUE THREAD

**Issue by PaddaelsM** [BioThemenVergabe/project#80]
*TODO*
- [x]  Cookiemeldung Größer machen
- [x] Cookietext anpassen: "nur wenn akzeptiert  kann 
- [x] bei /profile/save matrnr und email unique überprüfen 
- [x] Wenn bei /profile/save password (Wdh) nicht übereinstimmt -> Rückmeldung an user 
- [x] Bei Wahl: attribute: leiter + Plätze + Zeitpunkt hinzufügen 
- [x] /dashboard wenn wahl geschlossen, user darünber informieren 
- [x] Wenn wahl geschlossen, dürfen sich keine neuen Nutzer registrieren 
- [x] Passwort vergessen funktion auskommentieren 
- [x] Register modal --> form validate 

 

*BUGS*
- [x]  Non-stop reload des Dashboards 
- [x] /profile/save Error:Validator 
- [x] passwort ändern bei user funktioniert noch nicht

_Bitte einfach bearbeiten, wenn ein Bug gefunden wurde, oder eine Liste anfügen._
